# Jekyll configuration for GitHub Pages
title: Jekyll POC
description: A Jekyll site using the minimal theme
url: "https://patelkunal.github.io"
baseurl: "/jekyll-poc"
repository: patelkunal/jekyll-poc

# Theme configuration
remote_theme: pages-themes/minimal@v0.2.0

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Markdown processor
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Include files that start with underscore
include:
  - _pages

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "Your Name"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Site settings
author: Kunal Patel
email: kunal@example.com
twitter_username: patelkunal
github_username: patelkunal

# Build settings
safe: true
